export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const DISCOVER_GAME_ROUTE = '/'
export const REDUX_ROUTE = '/redux'
export const MOBX_ROUTE = '/mobx'
export const DEVICE_ROUTE = '/device'